### PR TITLE
Update Omnipay to v3

### PR DESCRIPTION
**Pull request by itsip**
This pull request updates Omnipay to v3 and makes the necessary changes to the package to comply with the update.

image

### CODE REVIEW

**Comment by Kcharle** [comment]
@aperdomo @robotpony @dhalarewich @lemonstandops 

Wondering if any of you are able to look at this PR :)

**Comment by Kcharle** [comment]
@aperdomo @robotpony @dhalarewich @lemonstandops 

Could someone merge this :) It's all clear and good to go

**Comment by Kcharle** [comment]
@aperdomo thanks for merging this! Do you mind tagging a release?

**Comment by Kcharle** [comment]
@aperdomo Do you mind tagging a release please 😄 👍

**Comment by tszulc** [comment]
@aperdomo, would you mind, and be able to cut a release with this update please?

**Comment by toommz** [comment]
@aperdomo any update on making a new release ?

**Pull request merged**
