### PR TITLE
Implemented Refund, Void, and Capture methods plus added testing

### PR DESCRIPTION
**Pull request by dcaswel**
This request contains implementations of the Refund, Void, and Capture requests. I also added testing for those requests as well as an integration test class for testing the functionality while it is actually interacting with Beanstream.

### CODE REVIEW

**Comment by dcaswel** [comment]
@aperdomo The output from travis-ci is a little vague. Could you shine some light on why the checks are failing for this PR? Thanks!

**Comment by dcaswel** [comment]
So...I must have been blind when I looked at the output from the CI before. I guess I was just looking at the red text at the bottom. :)

**Review by aperdomo — APPROVED** [review]
@CaswellWC 

Sorry for the delay on this - PR looks good.

**Comment by dcaswel** [comment]
@aperdomo 
No problem. If you feel comfortable doing so, I would appreciate it if this could get put into a new release as well. Thanks!

**Pull request merged**
